const LOAD_COMMENTS = 'LOAD_COMMENTS'
const LOAD_POSTS = 'LOAD_POSTS'
const LOAD_SINGLE_USERS = 'LOAD_SINGLE_USERS'
const LOAD_USERS = 'LOAD_USERS'

export {
    LOAD_COMMENTS,
    LOAD_USERS,
    LOAD_POSTS,
    LOAD_SINGLE_USERS
}